### ISSUE TITLE
Integrate npm publish and link to npm package/version

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/sign-and-verify-core#2]
Right now we're manually publishing npm packages. We can instead integrate with github's publish options, as well as link to the npm repo, which shows the latest version

**Comment by stuartf** [comment]
It looks like @jchartrand already did the bulk of the set up in `.github/workflows/npm-publish.yml`

I've added a token to the github repo secrets, so this should work when creating a release, though it may require the merging of #15
